---

language: python
python: 2.7

sudo: true

addons:
  apt:
    packages:
      - python-apt
      - python-pip

install:
  - pip install ansible==2.4.0 ansible-lint
  - ansible --version
  - ansible-galaxy install timorunge.pmm-client --roles-path=./
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-lint tasks/main.yml
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
