---

- include_tasks: percona-official-repo.yml
  when: pmm_client_enabled

- include_tasks: install.yml
  when: pmm_client_enabled

- include_tasks: server-config.yml
  when: pmm_client_enabled

- include_tasks: client-services.yml
  when: pmm_client_enabled

- include_tasks: uninstall.yml
  when: not pmm_client_enabled
