---

- name: Ensure Percona APT repository
  apt:
    deb: "{{ pmm_client_debian_repo }}"
    state: present
  when: >
        (pmm_client_use_official_repo) and
        (ansible_os_family == "Debian")

- name: Ensure Percona YUM repository
  yum:
    name: "{{ pmm_client_redhat_repo }}"
    state: present
  when: >
        (pmm_client_use_official_repo) and
        (ansible_os_family == "RedHat")
