---

- name: Ensure Percona APT repository
  apt:
    deb: "{{ pmm_client_repo }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure Percona YUM repository
  yum:
    name: "{{ pmm_client_repo }}"
    state: present
  when: ansible_os_family == "RedHat"
